// <auto-generated />
using System;
using BCH.Infrasructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BCH.Infrasructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230305022638_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("BCH.Domain.Entities.BchInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BchInfos");
                });

            modelBuilder.Entity("BCH.Domain.Entities.BchInfo", b =>
                {
                    b.OwnsOne("BCH.Domain.ValueObjects.Info", "Info", b1 =>
                        {
                            b1.Property<int>("BchInfoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("BchInfoId");

                            b1.ToTable("BchInfos");

                            b1.WithOwner()
                                .HasForeignKey("BchInfoId");
                        });

                    b.Navigation("Info")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
