// <auto-generated />
using System;
using BCH.Infrasructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BCH.Infrasructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("BCH.Infrasructure.Models.BchInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BchInfos");
                });

            modelBuilder.Entity("BCH.Infrasructure.Models.BchInfo", b =>
                {
                    b.OwnsOne("BCH.Infrasructure.Models.BCH", "Bch", b1 =>
                        {
                            b1.Property<int>("BchInfoId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CallTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HighFeePerKb")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LastForkHash")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("LastForkHeight")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LatestUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("LowFeePerKb")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MediumFeePerKb")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("PeerCount")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PreviousHash")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreviousUrl")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("UnconfirmedCount")
                                .HasColumnType("INTEGER");

                            b1.HasKey("BchInfoId");

                            b1.ToTable("BchInfos");

                            b1.WithOwner()
                                .HasForeignKey("BchInfoId");
                        });

                    b.Navigation("Bch")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
